// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABKjfGspaJC1RdUh58YiHJZePzdtq8lcQ',
    appId: '1:974845979574:android:2b86fd1f80c1acf4f6af17',
    messagingSenderId: '974845979574',
    projectId: 'investmateapp-3e136',
    databaseURL: 'https://investmateapp-3e136-default-rtdb.firebaseio.com',
    storageBucket: 'investmateapp-3e136.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaH25FnN9AesCHxcsyzOOOjUIoYANW5IU',
    appId: '1:974845979574:ios:cc7a0280e45b919af6af17',
    messagingSenderId: '974845979574',
    projectId: 'investmateapp-3e136',
    databaseURL: 'https://investmateapp-3e136-default-rtdb.firebaseio.com/',
    storageBucket: 'investmateapp-3e136.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );
}
